/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PdiPdiIdRouteImport } from './routes/pdi.$pdiId'
import { Route as ColaboradorIdRouteImport } from './routes/colaborador.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdiPdiIdRoute = PdiPdiIdRouteImport.update({
  id: '/pdi/$pdiId',
  path: '/pdi/$pdiId',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorIdRoute = ColaboradorIdRouteImport.update({
  id: '/colaborador/$id',
  path: '/colaborador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
  '/pdi/$pdiId': typeof PdiPdiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
  '/pdi/$pdiId': typeof PdiPdiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
  '/pdi/$pdiId': typeof PdiPdiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/colaborador/$id' | '/pdi/$pdiId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/colaborador/$id' | '/pdi/$pdiId'
  id: '__root__' | '/' | '/auth' | '/colaborador/$id' | '/pdi/$pdiId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ColaboradorIdRoute: typeof ColaboradorIdRoute
  PdiPdiIdRoute: typeof PdiPdiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdi/$pdiId': {
      id: '/pdi/$pdiId'
      path: '/pdi/$pdiId'
      fullPath: '/pdi/$pdiId'
      preLoaderRoute: typeof PdiPdiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/$id': {
      id: '/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/colaborador/$id'
      preLoaderRoute: typeof ColaboradorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ColaboradorIdRoute: ColaboradorIdRoute,
  PdiPdiIdRoute: PdiPdiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
